"""Persistence interfaces. Services depend on these Protocols, not on Firestore."""
from typing import Protocol

Doc = dict


class Repository(Protocol):
    def create_case(self, case: Doc) -> None: ...
    def get_case(self, case_id: str) -> Doc | None: ...
    def update_case(self, case_id: str, fields: Doc) -> None: ...
    def list_cases(self, owner_uid: str) -> list[Doc]: ...
    def delete_case(self, case_id: str) -> None: ...

    def put_doc(self, case_id: str, collection: str, doc_id: str, data: Doc) -> None: ...
    def get_doc(self, case_id: str, collection: str, doc_id: str) -> Doc | None: ...
    def list_docs(self, case_id: str, collection: str) -> list[Doc]: ...

    def incr_daily_cases(self, uid: str, day: str) -> int: ...
    def incr_global_daily_cases(self, day: str) -> int: ...
    def add_audit(self, entry: Doc) -> None: ...
    def put_eval_run(self, run: Doc) -> None: ...


class MediaStore(Protocol):
    def put(self, case_id: str, name: str, data: bytes, mime: str) -> str: ...
    def get(self, path: str) -> bytes: ...
    def delete_case(self, case_id: str) -> None: ...
